import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "on-secondary-container": "#526478",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fdfcff",
        "on-tertiary-fixed": "#121d26",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#3d4853",
        "surface-container-low": "#f2f4f7",
        "on-primary-fixed": "#3d0600",
        "on-error-container": "#93000a",
        "surface-container": "#eceef1",
        "primary-container": "#da3612",
        "error-container": "#ffdad6",
        "tertiary-container": "#6a7682",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#091d2e",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#ffb4a4",
        "surface-container-highest": "#e0e3e6",
        background: "#f7f9fc",
        "tertiary-fixed": "#d8e4f1",
        surface: "#f7f9fc",
        "inverse-on-surface": "#eff1f4",
        "on-primary-fixed-variant": "#8c1800",
        "on-secondary-fixed-variant": "#36485b",
        "secondary-fixed": "#d1e4fb",
        "surface-bright": "#f7f9fc",
        "inverse-primary": "#ffb4a4",
        "primary-fixed": "#ffdad3",
        "on-primary-container": "#fffbff",
        "outline-variant": "#e5beb5",
        tertiary: "#525d69",
        "surface-variant": "#e0e3e6",
        "secondary-container": "#cfe2f9",
        primary: "#b32200",
        "on-surface-variant": "#5c403a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        outline: "#906f68",
        error: "#ba1a1a",
        secondary: "#4e6073",
        "surface-tint": "#b72300",
        "secondary-fixed-dim": "#b5c8df",
        "surface-dim": "#d8dadd",
        "tertiary-fixed-dim": "#bcc8d5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "15px",
        card_padding: "10px 15px",
        container_padding: "20px",
        sidebar_width: "220px",
        topbar_height: "50px",
      },
      fontFamily: {
        "page-title": ["var(--font-source-sans)"],
        "body-semibold": ["var(--font-source-sans)"],
        "label-sm": ["var(--font-source-sans)"],
        "body-reg": ["var(--font-source-sans)"],
        "tile-number": ["var(--font-source-sans)"],
        "sidebar-item": ["var(--font-source-sans)"],
        "panel-header": ["var(--font-source-sans)"],
      },
      fontSize: {
        "page-title": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-semibold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-reg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "tile-number": ["34px", { lineHeight: "40px", fontWeight: "700" }],
        "sidebar-item": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "panel-header": ["14px", { lineHeight: "20px", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;